INSERT INTO department (name) VALUES
                                  ('Sales'),
                                  ('Marketing'),
                                  ('Finance'),
                                  ('Human Resources'),
                                  ('Customer Service'),
                                  ('Research and Development'),
                                  ('IT (Information Technology)'),
                                  ('Operations'),
                                  ('Legal'),
                                  ('Procurement'),
                                  ('Product Development'),
                                  ('Quality Assurance'),
                                  ('Public Relations'),
                                  ('Administration'),
                                  ('Facilities Management'),
                                  ('Accounting'),
                                  ('Logistics'),
                                  ('Security'),
                                  ('Compliance');